### ISSUE TITLE
frontend implementation

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#33]
In condenser we need to replace:
 - existing discussion API's, including blog/feeds (get_discussions_by_X, get_blog_feed, get_user_feed)
 - follows APIs (get_followers/get_following)
 - discussion threads APIs (get_state)

----

- [ ] get hive up in dev/stage/prod https://github.com/steemit/hivemind/issues/30
- [ ] add hive support to steem-js https://github.com/steemit/steem-js/issues/305
- [ ] integrate hive into condenser https://github.com/steemit/condenser/issues/2180

**Comment by roadscape** [comment]
condenser issue: https://github.com/steemit/condenser/issues/2180

**Comment by relativityboy** [comment]
Currently, if running condenser off the `https://github.com/steemit/condenser/tree/2180-hive-integration` branch and hitting hive locally off 8082 You'll need to add these to your exports to your env.

```
export SDC_SERVER_HIVE_URL="http://localhost:8082"
export SDC_SERVER_HIVE_NONAPPB_URL="http://localhost:8082/legacy"
```

**Comment by roadscape** [comment]
Closing as mirror of https://github.com/steemit/condenser/issues/2180

**Comment by Pecking** [comment]
@roadscape How do I need to solve the following problem？
![6pto9 _uy3_ lg20573kkt](https://user-images.githubusercontent.com/27414779/40969507-a5ef774c-68ea-11e8-8edd-c6ff733b1595.png)
![guqsp5n_ sq5 t5tlmzggp](https://user-images.githubusercontent.com/27414779/40969523-b1df987a-68ea-11e8-8f95-9a4375cc8c0c.png)

**Comment by roadscape** [comment]
@Pecking I'm not sure your bug is relevant to this thread. I would recommend using https://api.steemit.com instead of your local node. The problem is probably that steem-js does not know how to specifically ask for `condenser_api`. This needs to be fixed but in the meantime api.steemit.com (jussi) performs the translation. If you have further issues please create a new issue on the condenser repo.
