### ISSUE TITLE
db tunings: test, apply, document

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#52]
Evaluate:
 - [x] postgres config tuning (mem usage, autovac)
 - [x] ~deferring of constraints~ (moved to #95: initial sync perf)
 - [x] ~disabling indexes during initial sync~ (moved to #95 -- initial sync perf)
 - [x] sync index tuning (done; read-side to be handled in #93)
 - [x] ~table partitioning~

**Comment by roadscape** [comment]
[Deferring of constraints](https://www.postgresql.org/docs/9.0/static/sql-createtable.html)

> DEFERRABLE
> NOT DEFERRABLE
>  This controls whether the constraint can be deferred. A constraint that is not deferrable will be checked immediately after every command. Checking of constraints that are deferrable can be postponed until the end of the transaction (using the SET CONSTRAINTS command). NOT DEFERRABLE is the default. **Currently, only UNIQUE, PRIMARY KEY, EXCLUDE, and REFERENCES (foreign key) constraints accept this clause. NOT NULL and CHECK constraints are not deferrable.**

**Comment by roadscape** [comment]
The biggest query issue right now with listen mode is the following query slows to a halt (i.e. 500ms). `VACUUM ANALYZE` brings it to well under 100ms.

```
SELECT post_id, author, permlink FROM hive_posts_cache WHERE is_paidout = '0' AND payout_at < :date
```

Relevant index:
```
INDEX hive_posts_cache_ix3 ON hive_posts_cache USING btree (payout_at) WHERE is_paidout = false
```

**Comment by roadscape** [comment]
https://www.postgresql.org/docs/9.4/static/runtime-config-resource.html

**Comment by roadscape** [comment]
The post payout sweep query quickly becomes the heaviest by far. Need move the payout sweep to in-memory payout queue (subtask of #16: 'in-memory payout queue') and/or examine  why the slowdown. I suspect this might be the only retrieval query against hive_posts_cache during sync/listen, and could be a sign of performance issues the API layer will face.

The main issue with the table is that it's large, fairly wide, and every update is a full one. #16 has another subtask for this ('events which affect payout/votes vs. content of posts') which should help prevent fragmentation. Besides this, we may need to look into partitioning the tables and definitely need to look at autovac params.

```
[DEBUG] total SQL time: 1800s
 85.2%  1533237ms    521.33avg     2941x -- SELECT post_id, author, permlink FROM hive_posts_cache WHERE is_paidout = '0' AND payout_at <= :date
  5.3%   94818ms      1.01avg    93974x -- UPDATE hive_posts_cache SET author = :author, permlink = :permlink, category = :category, depth = :depth, children = :children, title = :title, preview = :preview, body = :body, im
  1.5%   26630ms      0.57avg    46829x -- UPDATE hive_accounts SET proxy = :proxy, post_count = :post_count, reputation = :reputation, proxy_weight = :proxy_weight, vote_weight = :vote_weight, kb_used = :kb_used, active_at
  1.4%   25183ms      0.35avg    72779x -- SELECT tag FROM hive_post_tags WHERE post_id = :id
  1.2%   22499ms      0.56avg    40379x -- SELECT id FROM hive_posts WHERE author = :a AND permlink = :p
  1.1%   19431ms      0.73avg    26566x -- INSERT INTO hive_posts_cache (post_id, author, permlink, category, depth, children, title, preview, body, img_url, payout, promoted, payout_at, updated_at, created_at, rshares, vot
```

**Comment by roadscape** [comment]
```
- shared_buffers = 128MB
+ shared_buffers = 4096MB

  effective_cache_size = 4GB

- work_mem = 4MB
+ work_mem = 128MB
- maintenance_work_mem = 64MB
+ maintenance_work_mem = 1024MB

- synchronous_commit = on
+ synchronous_commit = off

- autovacuum_vacuum_scale_factor = 0.2
+ autovacuum_vacuum_scale_factor = 0.01
- autovacuum_analyze_scale_factor = 0.1
+ autovacuum_analyze_scale_factor = 0.005

- checkpoint_completion_target = 0.5
+ checkpoint_completion_target = 0.9
```

checkpoint_segments
checkpoint_completion_target

**Comment by roadscape** [comment]
```
- effective_cache_size = 4GB
+ effective_cache_size = 12GB

- work_mem = 128MB
+ work_mem = 512MB

- maintenance_work_mem = 1024MB
+ maintenance_work_mem = 2GB

- random_page_cost = 4.0
+ random_page_cost = 1.0
```

**Comment by roadscape** [comment]
```
-- defaults

ALTER TABLE hive_accounts    SET (autovacuum_vacuum_scale_factor = 0.2);
ALTER TABLE hive_accounts    SET (autovacuum_analyze_scale_factor = 0.1);

ALTER TABLE hive_state       SET (autovacuum_vacuum_scale_factor = 0.2);
ALTER TABLE hive_state       SET (autovacuum_analyze_scale_factor = 0.1);

-- more aggresive

ALTER TABLE hive_posts       SET (autovacuum_vacuum_scale_factor = 0.01);
ALTER TABLE hive_posts       SET (autovacuum_analyze_scale_factor = 0.005);

ALTER TABLE hive_post_tags   SET (autovacuum_vacuum_scale_factor = 0.01);
ALTER TABLE hive_post_tags   SET (autovacuum_analyze_scale_factor = 0.005);

ALTER TABLE hive_feed_cache  SET (autovacuum_vacuum_scale_factor = 0.01);
ALTER TABLE hive_feed_cache  SET (autovacuum_analyze_scale_factor = 0.005);

-- very aggresive

ALTER TABLE hive_posts_cache SET (autovacuum_vacuum_scale_factor  = 0.0050); -- @ 36M posts, every 180k (~240k new posts/day)
ALTER TABLE hive_posts_cache SET (autovacuum_analyze_scale_factor = 0.0025); -- @ 36M posts, every 90k

ALTER TABLE hive_blocks      SET (autovacuum_vacuum_scale_factor  = 0.0100); -- @ 20M blocks, once a week
ALTER TABLE hive_blocks      SET (autovacuum_analyze_scale_factor = 0.0014); -- @ 20M blocks, once a day

ALTER TABLE hive_follows     SET (autovacuum_vacuum_scale_factor  = 0.0050); -- @ 47M follows, once a day (~300k new follows/day)
ALTER TABLE hive_follows     SET (autovacuum_analyze_scale_factor = 0.0025); -- @ 47M follows, 2-3 times a day

# consider using scale_factor = 0 with a flat threshold:
#autovacuum_vacuum_threshold  = 50  # row updates before vacuum
#autovacuum_analyze_threshold = 50  # row updates before analyze
```

**Comment by roadscape** [comment]
basic config added to readme in https://github.com/steemit/hivemind/commit/d3757f8cf93cdd9049d1bc7dfd861e7e763dd7c4
autovac tuning added to setup in https://github.com/steemit/hivemind/commit/4ad89a0680eb0c15461da96280da309fa6a51c32

**Comment by bobinson** [comment]
any plan to use multiple (primary - secondary) postgreSQL setup ? Just curious as WAL etc will come into picture in that scenario.

**Comment by roadscape** [comment]
@bobinson currently the plan is for each instance to have its own db; a separate trailing service creates snapshots to quickly initialize new instances.

**Comment by bobinson** [comment]
so, every node is complete with the logic and the data-store.

1. How will we scale ? We will not be able to horizontally scale as the logic is not independent of the db
2. If we take out the db / data-store from these instances, we can scale the logic layer horizontally and apply sharading etc on the db to scale ?

Just curious. 

>a separate trailing service creates snapshots to quickly initialize new instances.

So, the performance criteria should also try to include the "snapshot" process to capture the full life-cycle of the application ?

**Comment by roadscape** [comment]
@bobinson - hive does not require this specific configuration, but it should suffice for now. For the hive indexer, the vast majority of time is spent between reading from upstream and writing to db.

The snapshot process alleviates initial sync time; it's important to keep an eye on how long it takes, but real-time chain indexing and API performance are far more critical.

**Comment by roadscape** [comment]
```
- checkpoint_timeout = 5min
+ checkpoint_timeout = 30min

- max_wal_size = 1GB
+ max_wal_size = 4GB
```

**Comment by roadscape** [comment]
Initial sync concerns moved to #95 and awaiting test results; everything else complete.

**Comment by roadscape** [comment]
autovacuum/autoanalyze stats after a few days of operation, looks reasonable:

```
     relname      |  sf   | last_vacuum | last_autovacuum  |     n_tup      |    dead_tup    |  av_threshold  | expect_av | last_analyze | last_autoanalyze | vacuum_count | autovacuum_count | analyze_count | autoanalyze_count
------------------+-------+-------------+------------------+----------------+----------------+----------------+-----------+--------------+------------------+--------------+------------------+---------------+-------------------
 hive_follows     | 0.005 |             | 2018-02-27 22:30 |     49,818,488 |        220,487 |        249,142 |           |              | 2018-03-02 06:49 |            0 |                2 |             0 |                13
 hive_posts_cache | 0.005 |             | 2018-03-02 06:29 |     36,921,216 |        425,835 |        184,656 | *         |              | 2018-03-02 06:38 |            0 |                6 |             0 |                11
 hive_posts       |  0.01 |             |                  |     33,824,896 |         40,426 |        338,299 |           |              | 2018-03-02 01:25 |            0 |                0 |             0 |                 7
 hive_post_tags   |  0.01 |             |                  |     26,052,486 |         35,668 |        260,575 |           |              | 2018-03-02 01:36 |            0 |                0 |             0 |                 6
 hive_blocks      |  0.01 |             |                  |     20,320,516 |          2,033 |        203,255 |           |              | 2018-03-02 08:23 |            0 |                0 |             0 |                 6
 hive_feed_cache  |  0.01 |             |                  |     10,936,753 |         64,004 |        109,418 |           |              | 2018-03-01 18:56 |            0 |                0 |             0 |                 6
 hive_reblogs     |   0.2 |             |                  |      3,289,994 |          1,070 |        658,049 |           |              |                  |            0 |                0 |             0 |                 0
 hive_accounts    |   0.2 |             | 2018-03-02 07:57 |      1,388,210 |        345,826 |        277,692 | *         |              | 2018-03-02 08:03 |            0 |               11 |             0 |                20
 hive_payments    |   0.2 |             |                  |          8,598 |             20 |          1,770 |           |              | 2018-03-01 18:29 |            0 |                0 |             0 |                 5
 hive_state       |   0.2 |             | 2018-03-02 11:03 |              1 |             46 |             50 |           |              | 2018-03-02 11:03 |            0 |               54 |             0 |                54
```
